name: 'Build & Push Image'
description: 'Push image to ECR'
inputs:
  service:
    required: true
    type: string
  file-dir:
    required: true
    type: string
  registry:
    required: true
    type: string
  context:
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        buildkitd-flags: --debug
    - name: Cache Docker
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.service }}-v2-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.service }}-v2-
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file-dir }}/dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ inputs.registry }}/central-${{ inputs.service }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
