FROM public.ecr.aws/docker/library/node:16.14.2-alpine3.15 AS base
WORKDIR /app
# isntall pnpm
RUN apk --no-cache add libc6-compat
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    npm install -g pnpm@7.9.0

FROM base AS build
# Copy package.json and package-lock.json before other files
# Utilise Docker cache to save re-installing dependencies if unchanged
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./

# Install dependencies & build
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile \
    | grep -v "cross-device link not permitted\|Falling back to copying packages from store"
RUN apk --no-cache add git
COPY ./ ./
RUN pnpm build
RUN rm -rf node_modules \
	&& pnpm -r exec -- rm -rf node_modules

# Final image
FROM base
RUN npm install --global pm2

COPY --from=build /app .

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile --prod \
    | grep -v "cross-device link not permitted\|Falling back to copying packages from store"

EXPOSE 3000

CMD [ "pm2-runtime", "npm", "--", "start" ]