FROM node:16-alpine3.16 AS base
WORKDIR /app
# isntall pnpm
RUN apk --no-cache add libc6-compat
RUN npm install -g pnpm@7.9.0

FROM base AS build
# Copy package.json and package-lock.json before other files
# Utilise Docker cache to save re-installing dependencies if unchange
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./

# Install dependencies & build  
RUN pnpm install --frozen-lockfile 
RUN apk --no-cache add git
COPY ./ ./
RUN pnpm build
RUN rm -rf node_modules \
	&& pnpm -r exec -- rm -rf node_modules

# Final image
FROM base
RUN npm install --global pm2

COPY --from=build /app .

RUN pnpm install --frozen-lockfile --prod

EXPOSE 3000

CMD [ "pm2-runtime", "npm", "--", "start" ]