FROM lukemathwalker/cargo-chef:0.1.39-rust-latest AS chef
WORKDIR /gateway

FROM chef AS planner
COPY . .
RUN cargo chef prepare --bin services/gateway --recipe-path recipe.json

FROM chef AS cacher 
COPY --from=planner /gateway/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --bin gateway --recipe-path recipe.json

FROM chef as builder
# Build gatewaylication
COPY --from=cacher /gateway/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
COPY . .
RUN cargo build --release -p gateway

# We do not need the Rust toolchain to run the binary! need rebuil
FROM debian:buster-slim AS runtime
WORKDIR /gateway
COPY --from=builder /gateway/target/release/gateway /usr/local/bin

EXPOSE 4000
ENTRYPOINT ["/usr/local/bin/gateway"]