FROM lukemathwalker/cargo-chef:latest-rust-latest AS chef
WORKDIR /gateway

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /gateway/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --bin gateway

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR /gateway
COPY --from=builder /gateway/target/release/gateway /usr/local/bin

EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/gateway"]