FROM lukemathwalker/cargo-chef:latest-rust-latest AS chef
WORKDIR /crud

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /crud/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --bin crud

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR /crud
RUN apt-get update && apt-get install libpq5 -y
COPY --from=builder /crud/target/release/crud /usr/local/bin

EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/crud"]