FROM rust as build

# create a new empty shell project
RUN USER=root cargo new --bin central-crud
WORKDIR /central-crud

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
RUN cargo build --release
RUN rm src/*.rs

# copy your source tree
COPY ./migrations ./migrations
COPY ./src ./src

# build for release
RUN rm ./target/release/deps/central_crud*
RUN cargo build --release

# our final base
FROM debian:buster-slim

RUN apt-get update && apt-get install libpq5 -y

# copy the build artifact from the build stage
COPY --from=build /central-crud/target/release/central-crud .

EXPOSE 8080

# set the startup command to run your binary
CMD ["./central-crud"]