FROM rust:bullseye AS chef
WORKDIR /gateway
RUN cargo install cargo-chef
# force build
FROM chef AS planner
COPY . .
RUN cargo chef prepare --bin services/payments --recipe-path recipe.json

FROM chef AS cacher 
COPY --from=planner /payments/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --bin payments --recipe-path recipe.json

FROM chef as builder
# Build paymentslication
COPY --from=cacher /payments/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
COPY . .
RUN cargo build --release -p payments

# We do not need the Rust toolchain to run the binary!
FROM debian:bullseye-slim AS runtime
WORKDIR /payments
COPY --from=builder /payments/target/release/payments /usr/local/bin

RUN apt-get update && apt-get install openssl ca-certificates

EXPOSE 6000
CMD ["/usr/local/bin/payments"]