name: CRUD Build & Test

on: workflow_call

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: 'postgres://central_server:cntrl@localhost/central'
  JWT_SECRET: 'my actual secret, please dont hack me'

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/crud

    steps:
    - uses: actions/checkout@v3
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
      with:
        key: 'central-crud-cache'
    - name: Build
      run: cargo build --verbose
    - name: Start PostgreSQL on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    # Change user name and password to meet your requirements
    - name: Create additional user
      run: |
        sudo -u postgres psql --command="CREATE USER central_server PASSWORD 'cntrl'" --command="\du"
    # Change database name to meet your requirements
    - name: Create additional database
      run: |
        sudo -u postgres createdb --owner=central_server central
        PGPASSWORD=cntrl psql --username=central_server --host=localhost --list central
    - uses: taiki-e/install-action@v1
      with:
        tool: nextest
        ## version (defaults to "latest") can be a series like 0.9:
        version: 0.9
    - name: Run tests
      run: cargo nextest run --verbose
