on:
  push:
    branches:
      - main

jobs:
  crud-changes:
    uses: ./.github/workflows/changes.yml
    with:
      path: services/crud/**

  crud-ci:
    needs: crud-changes
    #if: needs.crud-changes.outputs.changed == 'true' COMMENT OUT FOR TESTING
    uses: ./.github/workflows/crud-ci.yml

  crud:
    runs-on: ubuntu-latest
    needs: crud-ci
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build Image
        run: docker build . -f ./services/crud/dockerfile -t central-crud:latest
      - name: Push to ECR
        uses: ./.github/push-image
        with:
          repo: central-crud
          access-key: ${{ secrets.ECR_ACCESS_KEY }}
          secret-key: ${{ secrets.ECR_SECRET_KEY }}
