on:
  push:
    branches:
      - main

jobs:
  crud-changes:
    uses: ./.github/workflows/changes.yml
    with:
      path: services/crud/**

  crud-ci:
    uses: ./.github/workflows/crud-ci.yml

  push-crud:
    runs-on: ubuntu-latest
    needs: [crud-ci, crud-changes]
    steps:
      - uses: actions/checkout@v3
        if: needs.crud-changes.outputs.changed == 'true'
      - uses: satackey/action-docker-layer-caching@v0.0.11
        if: needs.crud-changes.outputs.changed == 'true'
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build Image
        if: needs.crud-changes.outputs.changed == 'true'
        run: docker build . -f ./services/crud/dockerfile -t central-crud:latest
      - name: Push to ECR
        if: needs.crud-changes.outputs.changed == 'true'
        uses: ./.github/push-image
        with:
          repo: central-crud
          access-key: ${{ secrets.ECR_ACCESS_KEY }}
          secret-key: ${{ secrets.ECR_SECRET_KEY }}

  gateway-changes:
    uses: ./.github/workflows/changes.yml
    with:
      path: services/gateway/**

  gateway-ci:
    uses: ./.github/workflows/gateway-ci.yml

  push-gateway:
    runs-on: ubuntu-latest
    needs: [gateway-ci, gateway-changes]
    steps:
      - uses: actions/checkout@v3
        if: needs.gateway-changes.outputs.changed == 'true'
      - uses: satackey/action-docker-layer-caching@v0.0.11
        if: needs.gateway-changes.outputs.changed == 'true'
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build Image
        if: needs.gateway-changes.outputs.changed == 'true'
        run: docker build . -f ./services/gateway/dockerfile -t central-gateway:latest
      - name: Push to ECR
        if: needs.gateway-changes.outputs.changed == 'true'
        uses: ./.github/push-image
        with:
          repo: central-gateway
          access-key: ${{ secrets.ECR_ACCESS_KEY }}
          secret-key: ${{ secrets.ECR_SECRET_KEY }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: [push-gateway, push-crud]
    steps:
      - run: echo "pretend this is deploying"
