on:
  push:
    branches:
      - main

jobs:
  crud-changes:
    uses: ./.github/workflows/changes.yml
    with:
      path: services/crud/**

  crud:
    runs-on: ubuntu-latest
    needs: crud-changes
    #if: needs.crud-changes.outputs.changed == 'true' COMMENT OUT FOR TESTING
    steps:
      - name: Build & Test
        uses: ./.github/workflows/crud-ci.yml
      - name: Build Image
        run: docker build ./services/crud -t central-crud:latest
      - name: Push to ECR
        uses: ./.github/workflows/ecr-setup.yml
        with:
          repo: central-crud
          access-key: ${{ secrets.AWS_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_SECRET_KEY }}
