name: Payments Build & Test

on: workflow_call

env:
  CARGO_TERM_COLOR: always
  # TODO real tests and secrets

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/payments

    steps:
    - uses: actions/checkout@v3
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
      with:
        key: 'central-payments-cache'
    - name: Build
      run: cargo build --verbose
    - uses: taiki-e/install-action@v1
      with:
        tool: nextest
    - name: Run tests
      run: cargo nextest run --verbose
