name: 'Login To ECR'
description: 'Push image to ECR'
inputs:
  access-key:
    required: true
    type: string
  secret-key:
    required: true
    type: string
outputs:
  registry:
    value: ${{ steps.ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.access-key }}
        aws-secret-access-key: ${{ inputs.secret-key }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1
